# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Use secret in Java code
      run: |
        export USERNAME=${{ secrets.USERNAME }}
        export PASSWORD=${{ secrets.PASSWORD }}
        export AUTHORIZATION=${{ secrets.AUTHORIZATION }}
        # Use the exported environment variable in your Java application

    - name: Build with Maven
      run: mvn clean install

    - name: Run it
      run: java -jar target/reddit-watcher-1.0-SNAPSHOT-jar-with-dependencies.jar

    - name: Create csvs directory
      run: mkdir -p ./csvs/

    - name: Find and Publish csvs
      run: |
        git config --global user.name 'Zreddit'
        git config --global user.email 'Zreddit59@techie.com'
        git checkout -b csvs
        csv_path=$(find . -name "topics.csv")
        if [ -z "$csv_path" ]; then
          echo "topic.csv not found in the workspace."
        else
          cp $csv_path ./csvs/
          git add ./csvs/topics.csv
          git commit -m "Add csvs"
          git push origin csvs
        fi


    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #    - name: Update dependency graph
    #      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
